### ISSUE TITLE
Erro na paginação

### ISSUE THREAD

**Issue by angelosds** [foster-hub/box-cms#2]
No site que estamos desenvolvendo utilizando o Box, encontramos um erro na paginação, sempre que uma lista possui uma quantidade de itens equivalente à quantidade definida na paginação, o botão de navegar para a próxima página é exibido quando estamos na última página.

**Ex.:** Possuo uma listagem de notícias com 20 itens e defini a paginação como 10 itens por página, o que resulta em 2 páginas para navegar. Na primeira página o botão de "próxima página" é exibido e me redireciona para a segunda página, na segunda página o botão de próxima página continua sendo exibido e me redireciona para uma terceira página. Como a lista possui apenas 20 itens, a terceira página exibe a mensagem "No items".

**Comment by marcos-foster** [comment]
Opa...resolvido no **commit 2fb72cc**.
Enquanto não libero a nova release, precisa copiar os seguintes arquivos atualizados:

- scripts\box.contentesasyncVM.js
- bin\box.cms.dll

Atualizei o exemplo de uso também em: news.cshtml exemplo
